### ISSUE TITLE
Make "all paths" json file

### ISSUE THREAD

**Issue by mfranzs** [MIT-6819-team/TF_colorization#15]

**Comment by kocabey** [comment]
I created all the paths for the ImageNet Data.

file path: `/afs/csail.mit.edu/u/k/kocabey/Notebooks/Colorization Project/all_paths.txt` [1281146 lines]

**Comment by Winter-Guerra** [comment]
@kocabey could you please commit the file to github so that we can sync it to our local computers?

**Comment by kocabey** [comment]
I cannot actually commit the txt file because it is larger than 100MB [Github doesn't accept files bigger than 25MB]. You can download it from my server.
