### ISSUE TITLE
Reimplement https://github.com/richzhang/colorization in TF

### ISSUE THREAD

**Issue by Winter-Guerra** [MIT-6819-team/TF_colorization#3]
Hopefully with results that are somewhat comparable to that of the paper (accounting for reduced epochs, etc.)/

**Comment by mfranzs** [comment]
- [] Divine meaning into what the 313 magic number is#1 
- [] Loss func#6 
- []

**Comment by Winter-Guerra** [comment]
Closing since this issue is kinda redundant and will be hard to keep updated.
